import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import '../models/rutina_adaptacion_model.dart';

class SeedRutinasService {
  static Future<void> inyectarDatos(BuildContext context) async {
    final db = FirebaseFirestore.instance;
    final collection = db.collection('rutinas_adaptacion');

    try {
      // 1. Variante 3 Días (Original Full Body)
      final rutina3Dias = RutinaAdaptacion(
        id: 'fullbody_3_dias',
        variante: '3 Días',
        dias: [
          DiaRutina(
            nombreDia: 'Lunes',
            ejercicios: [
              Ejercicio(
                nombre: 'Prensa de Piernas',
                tipo: 'Máquina',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/leg_press.png',
              ),
              Ejercicio(
                nombre: 'Flexiones de Brazo',
                tipo: 'Peso Corporal',
                seriesReps: '3x10',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/pushup.png',
              ),
              Ejercicio(
                nombre: 'Jalón al Pecho',
                tipo: 'Máquina',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
              ),
              Ejercicio(
                nombre: 'Sentadillas Libres',
                tipo: 'Peso Corporal',
                seriesReps: '3x15',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/squat.png',
              ),
              Ejercicio(
                nombre: 'Remo en Máquina',
                tipo: 'Máquina',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
              ),
              Ejercicio(
                nombre: 'Plancha Abdominal',
                tipo: 'Peso Corporal',
                seriesReps: '3x45 seg',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/plank.png',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Miércoles',
            ejercicios: [
              Ejercicio(
                nombre: 'Sentadilla Goblet',
                tipo: 'Peso Libre',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/squat.png',
              ),
              Ejercicio(
                nombre: 'Press de Pecho Máquina',
                tipo: 'Máquina',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
              ),
              Ejercicio(
                nombre: 'Remo con Mancuerna',
                tipo: 'Peso Libre',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
              ),
              Ejercicio(
                nombre: 'Extensiones de Cuádriceps',
                tipo: 'Máquina',
                seriesReps: '3x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/leg_extension.png',
              ),
              Ejercicio(
                nombre: 'Crunch Abdominal',
                tipo: 'Peso Corporal',
                seriesReps: '3x20',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/plank.png',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Viernes',
            ejercicios: [
              Ejercicio(
                nombre: 'Prensa de Piernas',
                tipo: 'Máquina',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/leg_press.png',
              ),
              Ejercicio(
                nombre: 'Flexiones de Brazo',
                tipo: 'Peso Corporal',
                seriesReps: '3x10',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/pushup.png',
              ),
              Ejercicio(
                nombre: 'Jalón al Pecho',
                tipo: 'Máquina',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
              ),
              Ejercicio(
                nombre: 'Sentadillas Libres',
                tipo: 'Peso Corporal',
                seriesReps: '3x15',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/squat.png',
              ),
              Ejercicio(
                nombre: 'Plancha Abdominal',
                tipo: 'Peso Corporal',
                seriesReps: '3x45 seg',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/plank.png',
              ),
            ],
          ),
        ],
      );

      // 2. Variante 5 Días
      final rutina5Dias = RutinaAdaptacion(
        id: 'fullbody_5_dias',
        variante: '5 Días',
        dias: [
          DiaRutina(
            nombreDia: 'Día 1 - Piernas',
            ejercicios: [
              Ejercicio(
                nombre: 'Sentadilla en Máquina',
                tipo: 'Máquina',
                seriesReps: '4x12',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/squat.png',
              ),
              Ejercicio(
                nombre: 'Prensa',
                tipo: 'Máquina',
                seriesReps: '4x12',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/leg_press.png',
              ),
              Ejercicio(
                nombre: 'Extensión Cuádriceps',
                tipo: 'Máquina',
                seriesReps: '3x15',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/leg_extension.png',
              ),
              Ejercicio(
                nombre: 'Estocadas',
                tipo: 'Peso Corporal',
                seriesReps: '3x12 por pierna',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lunge.png',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Día 2 - Empuje',
            ejercicios: [
              Ejercicio(
                nombre: 'Press Pecho Máquina',
                tipo: 'Máquina',
                seriesReps: '4x10',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
              ),
              Ejercicio(
                nombre: 'Press Hombros Máquina',
                tipo: 'Máquina',
                seriesReps: '4x10',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
              ),
              Ejercicio(
                nombre: 'Extensiones Triceps',
                tipo: 'Polea',
                seriesReps: '3x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/triceps_extension.png',
              ),
              Ejercicio(
                nombre: 'Flexiones Apoyo Rodillas',
                tipo: 'Peso Corporal',
                seriesReps: '3xFallo',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/pushup.png',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Día 3 - Tracción',
            ejercicios: [
              Ejercicio(
                nombre: 'Jalón Polea Alta',
                tipo: 'Polea',
                seriesReps: '4x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
              ),
              Ejercicio(
                nombre: 'Remo Gironda',
                tipo: 'Polea',
                seriesReps: '4x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
              ),
              Ejercicio(
                nombre: 'Curl Biceps Polea',
                tipo: 'Polea',
                seriesReps: '3x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/biceps_curl.png',
              ),
              Ejercicio(
                nombre: 'Dominadas Asistidas',
                tipo: 'Máquina',
                seriesReps: '3x10',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Día 4 - Glúteo e Isquios',
            ejercicios: [
              Ejercicio(
                nombre: 'Peso Muerto Rumano',
                tipo: 'Peso Libre',
                seriesReps: '4x12',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/hamstring_curl.png',
              ),
              Ejercicio(
                nombre: 'Curl Isquios Tumbado',
                tipo: 'Máquina',
                seriesReps: '4x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/hamstring_curl.png',
              ),
              Ejercicio(
                nombre: 'Hip Thrust Asistido',
                tipo: 'Máquina',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/hamstring_curl.png',
              ),
              Ejercicio(
                nombre: 'Elevación de Piernas',
                tipo: 'Peso Corporal',
                seriesReps: '4x20',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/plank.png',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Día 5 - Full Body',
            ejercicios: [
              Ejercicio(
                nombre: 'Sentadillas Globales',
                tipo: 'Peso Corporal',
                seriesReps: '3x20',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/squat.png',
              ),
              Ejercicio(
                nombre: 'Flexiones Abiertas',
                tipo: 'Peso Corporal',
                seriesReps: '3x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/pushup.png',
              ),
              Ejercicio(
                nombre: 'Jalón en V',
                tipo: 'Polea',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
              ),
              Ejercicio(
                nombre: 'Plancha Spiderman',
                tipo: 'Peso Corporal',
                seriesReps: '3x15/lado',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/plank.png',
              ),
            ],
          ),
        ],
      );

      // 3. Rutina Principiante - Variante 3 Días
      final rutinaPrincipiante3Dias = RutinaAdaptacion(
        id: 'principiante_3_dias',
        variante: '3 Días',
        dias: [
          DiaRutina(
            nombreDia: 'Día 1',
            ejercicios: [
              Ejercicio(
                nombre: 'Press de Pecho en Máquina',
                tipo: 'Máquina',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                instruccion:
                    'Mantené la espalda apoyada y empujá controlando el movimiento.',
              ),
              Ejercicio(
                nombre: 'Aperturas Inclinadas',
                tipo: 'Mancuernas',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/pushup.png',
                instruccion:
                    'Abrí los brazos sintiendo el estiramiento en el pecho y cerrá.',
              ),
              Ejercicio(
                nombre: 'Jalón al Pecho',
                tipo: 'Máquina',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
                instruccion:
                    'Llevá la barra hacia el pecho superior, juntando las escápulas.',
              ),
              Ejercicio(
                nombre: 'Remo con Mancuerna',
                tipo: 'Mancuernas',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                instruccion:
                    'Apoyá una rodilla y mano en un banco. Tirá de la mancuerna hacia tu cadera.',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Día 2',
            ejercicios: [
              Ejercicio(
                nombre: 'Prensa de Piernas',
                tipo: 'Máquina',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/leg_press.png',
                instruccion:
                    'Pies separados ancho de hombros. Bajá hasta 90 grados y empujá con los talones.',
              ),
              Ejercicio(
                nombre: 'Extensiones de Cuádriceps',
                tipo: 'Máquina',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/leg_extension.png',
                instruccion:
                    'Extendé las piernas completamente sin dar tirones. Bajá lento.',
              ),
              Ejercicio(
                nombre: 'Sentadilla Goblet',
                tipo: 'Mancuerna',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/squat.png',
                instruccion:
                    'Sostené la mancuerna en el pecho. Mantené la espalda recta al bajar.',
              ),
              Ejercicio(
                nombre: 'Estocadas con Mancuernas',
                tipo: 'Mancuernas',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lunge.png',
                instruccion:
                    'Dá un paso largo, bajando la cadera en vertical. Alterná piernas.',
              ),
              Ejercicio(
                nombre: 'Press Militar Sentado',
                tipo: 'Mancuernas',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                instruccion:
                    'Empujá las mancuernas hacia arriba por encima de la cabeza sin arquear la espalda.',
              ),
              Ejercicio(
                nombre: 'Vuelos Laterales',
                tipo: 'Mancuernas',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                instruccion:
                    'Elevá los brazos semiflexionados hasta la altura de los hombros.',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Día 3',
            ejercicios: [
              Ejercicio(
                nombre: 'Curl de Bíceps Alternado',
                tipo: 'Mancuernas',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/biceps_curl.png',
                instruccion:
                    'Mantené los codos pegados al cuerpo y flexioná alternando los brazos.',
              ),
              Ejercicio(
                nombre: 'Curl en Polea Baja',
                tipo: 'Polea',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/biceps_curl.png',
                instruccion:
                    'Movimiento continuo y controlado, apretando el bíceps arriba.',
              ),
              Ejercicio(
                nombre: 'Extensión de Tríceps',
                tipo: 'Polea',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/triceps_extension.png',
                instruccion:
                    'Codos fijos a los lados, extendé los brazos empujando hacia abajo.',
              ),
              Ejercicio(
                nombre: 'Press Francés Tumbado',
                tipo: 'Mancuernas',
                seriesReps: '3x12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/triceps_extension.png',
                instruccion:
                    'Tumbado, bajá las mancuernas al lado de la cabeza y extendé.',
              ),
            ],
          ),
        ],
      );

      // 4. Rutina Principiante - Variante 5 Días
      final rutinaPrincipiante5Dias = RutinaAdaptacion(
        id: 'principiante_5_dias',
        variante: '5 Días',
        dias: [
          DiaRutina(
            nombreDia: 'Lunes (Pecho)',
            ejercicios: [
              Ejercicio(
                nombre: 'Press de Banca Plano',
                tipo: 'Barra',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                instruccion:
                    'Bajá la barra al medio del pecho controlando la fase excéntrica y empujá con potencia.',
              ),
              Ejercicio(
                nombre: 'Press Inclinado',
                tipo: 'Mancuernas',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                instruccion:
                    'Incliná el banco a 30-45 grados. Mantené el abdomen firme para proteger la espalda baja.',
              ),
              Ejercicio(
                nombre: 'Peck Deck',
                tipo: 'Máquina',
                seriesReps: '3x10-12',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                instruccion:
                    'Mantené los codos ligeramente flexionados, apretando el pecho al frente como en un abrazo.',
              ),
              Ejercicio(
                nombre: 'Cruces',
                tipo: 'Polea',
                seriesReps: '3x10-12',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/pushup.png',
                instruccion:
                    'Paso firme adelante. Cruzá las manos frente al abdomen sintiendo la contracción torácica.',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Martes (Piernas)',
            ejercicios: [
              Ejercicio(
                nombre: 'Sentadilla',
                tipo: 'Barra',
                seriesReps: '3x10-12',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/squat.png',
                instruccion:
                    'Espalda recta, pecho arriba. Rompé el paralelo flexionando la cadera hacia atrás y abajo.',
              ),
              Ejercicio(
                nombre: 'Estocadas',
                tipo: 'Mancuerna',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lunge.png',
                instruccion:
                    'Paso largo, bajá controlando que la rodilla no pase en exceso la punta de los pies.',
              ),
              Ejercicio(
                nombre: 'Prensa',
                tipo: 'Máquina',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/leg_press.png',
                instruccion:
                    'Pies bien afirmados. Bajá las rodillas hacia el pecho y empujá con los talones sin bloquear arriba.',
              ),
              Ejercicio(
                nombre: 'Curl Femoral',
                tipo: 'Máquina',
                seriesReps: '3x10-12',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/hamstring_curl.png',
                instruccion:
                    'Tumbado, contraé el isquiosural arrastrando el peso hacia tus glúteos de forma fluida.',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Miércoles (Espalda)',
            ejercicios: [
              Ejercicio(
                nombre: 'Remo con Barra',
                tipo: 'Barra',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                instruccion:
                    'Incliná el torso a 45 grados. Tirá de la barra hacia el ombligo juntando las escápulas.',
              ),
              Ejercicio(
                nombre: 'Remo a una Mano',
                tipo: 'Mancuerna',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                instruccion:
                    'Apoyá rodilla y mano en banco. Traccioná la mancuerna en un arco hacia la cadera.',
              ),
              Ejercicio(
                nombre: 'Jalón al Pecho',
                tipo: 'Polea',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
                instruccion:
                    'Sentado firme, bajá la barra hacia el pecho expandiendo la caja torácica.',
              ),
              Ejercicio(
                nombre: 'Remo Sentado',
                tipo: 'Máquina',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                instruccion:
                    'Postura vertical estricta. Evitá balancearte con la espalda baja al traccionar el agarre.',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Jueves (Hombros)',
            ejercicios: [
              Ejercicio(
                nombre: 'Press Militar',
                tipo: 'Barra',
                seriesReps: '3x10-12',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                instruccion:
                    'Sostené la barra sobre la clavícula. Empujá vertical hasta extender brazos cerca de las orejas.',
              ),
              Ejercicio(
                nombre: 'Vuelos Laterales',
                tipo: 'Mancuerna',
                seriesReps: '3x10-12',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                instruccion:
                    'Movimiento de las mancuernas desde la cadera hacia la altura de los hombros, guiando con los codos.',
              ),
              Ejercicio(
                nombre: 'Press de Hombros',
                tipo: 'Máquina',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                instruccion:
                    'Sentado correctamente, empujá los agarres hacia el techo con un recorrido completo sin botar.',
              ),
              Ejercicio(
                nombre: 'Facepull',
                tipo: 'Polea',
                seriesReps: '3x10-12',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
                instruccion:
                    'Enganchá una soga y tirá directo hacia el puente de la nariz separando los codos.',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Viernes (Brazos)',
            ejercicios: [
              Ejercicio(
                nombre: 'Curl con Barra',
                tipo: 'Barra',
                seriesReps: '3x10-12',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/biceps_curl.png',
                instruccion:
                    'Posición firme de torso, flexioná ambos brazos elevando la carga sin impulsar con la cadera.',
              ),
              Ejercicio(
                nombre: 'Curl Alterno',
                tipo: 'Mancuerna',
                seriesReps: '3x10-12',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/biceps_curl.png',
                instruccion:
                    'Alternando un brazo a la vez. Exprimí el bíceps arriba supindanto la muñeca.',
              ),
              Ejercicio(
                nombre: 'Extensión Invertida',
                tipo: 'Polea',
                seriesReps: '3x10-12',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/triceps_extension.png',
                instruccion:
                    'Codos encajados en los flancos. Extendé llevando la soga hacia abajo y separando las puntas.',
              ),
              Ejercicio(
                nombre: 'Press Francés',
                tipo: 'Barra',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/triceps_extension.png',
                instruccion:
                    'Tumbado, bajá la barra tipo Z hacia la frente o justo detrás y finalizá la extensión arriba.',
              ),
            ],
          ),
        ],
      );

      // --- NEW: RUTINAS INTERMEDIAS ---
      final rutinaIntermedia3Dias = RutinaAdaptacion(
        id: 'intermedio_3_dias',
        variante: '3 Días',
        dias: [
          DiaRutina(
            nombreDia: 'Día 1: Fuerza Básica',
            ejercicios: [
              Ejercicio(
                nombre: 'Sentadilla con Barra',
                tipo: 'Barra',
                seriesReps: '4x6-8',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/squat.png',
                series: '4',
                repeticiones: '6-8',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Piernas',
              ),
              Ejercicio(
                nombre: 'Press de Banca Plano',
                tipo: 'Barra',
                seriesReps: '4x6-8',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '4',
                repeticiones: '6-8',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Pecho',
              ),
              Ejercicio(
                nombre: 'Remo con Barra',
                tipo: 'Barra',
                seriesReps: '4x6-8',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                series: '4',
                repeticiones: '6-8',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Espalda',
              ),
              Ejercicio(
                nombre: 'Press Militar',
                tipo: 'Barra',
                seriesReps: '3x8-10',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '3',
                repeticiones: '8-10',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Hombros',
              ),
              Ejercicio(
                nombre: 'Plancha Abdominal Lastrada',
                tipo: 'Peso Corporal',
                seriesReps: '3x45-60 seg',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/plank.png',
                series: '3',
                repeticiones: '45-60 seg',
                tipoDeEquipo: 'Bodyweight',
                musculoObjetivo: 'Core',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Día 2: Máquinas/Aislamiento',
            ejercicios: [
              Ejercicio(
                nombre: 'Prensa de Piernas',
                tipo: 'Máquina',
                seriesReps: '4x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/leg_press.png',
                series: '4',
                repeticiones: '10-12',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Piernas',
              ),
              Ejercicio(
                nombre: 'Press Inclinado en Máquina',
                tipo: 'Máquina',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '3',
                repeticiones: '10-12',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Pecho',
              ),
              Ejercicio(
                nombre: 'Jalón Dorsal',
                tipo: 'Máquina',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
                series: '3',
                repeticiones: '10-12',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Espalda',
              ),
              Ejercicio(
                nombre: 'Extensión de Cuádriceps',
                tipo: 'Máquina',
                seriesReps: '3x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/leg_extension.png',
                series: '3',
                repeticiones: '15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Cuádriceps',
              ),
              Ejercicio(
                nombre: 'Curl Femoral',
                tipo: 'Máquina',
                seriesReps: '3x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/hamstring_curl.png',
                series: '3',
                repeticiones: '15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Isquiosurales',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Día 3: Mixto',
            ejercicios: [
              Ejercicio(
                nombre: 'Peso Muerto Rumano',
                tipo: 'Mancuernas',
                seriesReps: '4x8-10',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/hamstring_curl.png',
                series: '4',
                repeticiones: '8-10',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Isquiosurales, Glúteos',
              ),
              Ejercicio(
                nombre: 'Estocadas Búlgaras',
                tipo: 'Mancuernas',
                seriesReps: '3x10/pierna',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lunge.png',
                series: '3',
                repeticiones: '10 / pierna',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Piernas',
              ),
              Ejercicio(
                nombre: 'Press Inclinado con Mancuernas',
                tipo: 'Mancuernas',
                seriesReps: '3x8-10',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '3',
                repeticiones: '8-10',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Pecho Superior',
              ),
              Ejercicio(
                nombre: 'Dominadas Asistidas o Libres',
                tipo: 'Peso Corporal',
                seriesReps: '3xAl Fallo',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
                series: '3',
                repeticiones: 'Al Fallo',
                tipoDeEquipo: 'Bodyweight',
                musculoObjetivo: 'Espalda',
              ),
              Ejercicio(
                nombre: 'Elevaciones Laterales',
                tipo: 'Mancuernas',
                seriesReps: '4x12-15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                series: '4',
                repeticiones: '12-15',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Hombros Laterales',
              ),
            ],
          ),
        ],
      );

      final rutinaIntermedia5Dias = RutinaAdaptacion(
        id: 'intermedio_5_dias',
        variante: '5 Días',
        dias: [
          DiaRutina(
            nombreDia: 'Lunes: Empuje',
            ejercicios: [
              Ejercicio(
                nombre: 'Press de Banca Plano',
                tipo: 'Barra',
                seriesReps: '4x6-8',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '4',
                repeticiones: '6-8',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Pecho',
              ),
              Ejercicio(
                nombre: 'Press Militar con Mancuernas',
                tipo: 'Mancuernas',
                seriesReps: '4x8-10',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '4',
                repeticiones: '8-10',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Hombros',
              ),
              Ejercicio(
                nombre: 'Aperturas Inclinadas',
                tipo: 'Mancuernas',
                seriesReps: '3x12',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/pushup.png',
                series: '3',
                repeticiones: '12',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Pecho Superior',
              ),
              Ejercicio(
                nombre: 'Elevaciones Laterales en Polea',
                tipo: 'Máquina',
                seriesReps: '4x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                series: '4',
                repeticiones: '15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Hombros Laterales',
              ),
              Ejercicio(
                nombre: 'Extensión Invertida Tríceps',
                tipo: 'Máquina',
                seriesReps: '3x12',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/triceps_extension.png',
                series: '3',
                repeticiones: '12',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Tríceps',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Martes: Tirón',
            ejercicios: [
              Ejercicio(
                nombre: 'Dominadas / Jalón al Pecho',
                tipo: 'Máquina',
                seriesReps: '4x8-10',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
                series: '4',
                repeticiones: '8-10',
                tipoDeEquipo: 'Bodyweight o Machine',
                musculoObjetivo: 'Espalda',
              ),
              Ejercicio(
                nombre: 'Remo con Barra',
                tipo: 'Barra',
                seriesReps: '4x8-10',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                series: '4',
                repeticiones: '8-10',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Espalda Baja',
              ),
              Ejercicio(
                nombre: 'Remo a una mano',
                tipo: 'Mancuerna',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                series: '3',
                repeticiones: '10-12',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Dorsales',
              ),
              Ejercicio(
                nombre: 'Facepull',
                tipo: 'Máquina',
                seriesReps: '3x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
                series: '3',
                repeticiones: '15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Deltoides posterior',
              ),
              Ejercicio(
                nombre: 'Curl de Bíceps Alternado',
                tipo: 'Mancueras',
                seriesReps: '3x12',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/biceps_curl.png',
                series: '3',
                repeticiones: '12',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Bíceps',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Miércoles: Pierna',
            ejercicios: [
              Ejercicio(
                nombre: 'Sentadilla Libre',
                tipo: 'Barra',
                seriesReps: '4x6-8',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/squat.png',
                series: '4',
                repeticiones: '6-8',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Cuádriceps, Glúteos',
              ),
              Ejercicio(
                nombre: 'Prensa',
                tipo: 'Máquina',
                seriesReps: '4x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/leg_press.png',
                series: '4',
                repeticiones: '10-12',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Piernas',
              ),
              Ejercicio(
                nombre: 'Peso Muerto Rumano',
                tipo: 'Barra',
                seriesReps: '3x8-10',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/hamstring_curl.png',
                series: '3',
                repeticiones: '8-10',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Isquiosurales',
              ),
              Ejercicio(
                nombre: 'Elevación de Talones a un Pie',
                tipo: 'Mancuerna',
                seriesReps: '4x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/squat.png',
                series: '4',
                repeticiones: '15',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Pantorrillas',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Jueves: Torso Hipertrofia',
            ejercicios: [
              Ejercicio(
                nombre: 'Press Inclinado con Mancuernas',
                tipo: 'Mancuernas',
                seriesReps: '4x8-10',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '4',
                repeticiones: '8-10',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Pecho Superior',
              ),
              Ejercicio(
                nombre: 'Remo en Máquina',
                tipo: 'Máquina',
                seriesReps: '4x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                series: '4',
                repeticiones: '10-12',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Espalda Central',
              ),
              Ejercicio(
                nombre: 'Press Militar Máquina',
                tipo: 'Máquina',
                seriesReps: '3x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '3',
                repeticiones: '10-12',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Hombros',
              ),
              Ejercicio(
                nombre: 'Curl de Bíceps en Polea',
                tipo: 'Máquina',
                seriesReps: '3x12-15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/biceps_curl.png',
                series: '3',
                repeticiones: '12-15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Bíceps',
              ),
              Ejercicio(
                nombre: 'Press Francés con Mancuerna',
                tipo: 'Mancuerna',
                seriesReps: '3x12-15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/triceps_extension.png',
                series: '3',
                repeticiones: '12-15',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Tríceps',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Viernes: Pierna/Glúteo',
            ejercicios: [
              Ejercicio(
                nombre: 'Hip Thrust',
                tipo: 'Barra',
                seriesReps: '4x8-10',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/lunge.png',
                series: '4',
                repeticiones: '8-10',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Glúteos',
              ),
              Ejercicio(
                nombre: 'Sentadilla Búlgara',
                tipo: 'Mancuerna',
                seriesReps: '3x10/pierna',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lunge.png',
                series: '3',
                repeticiones: '10 / pierna',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Piernas',
              ),
              Ejercicio(
                nombre: 'Extensión de Cuádriceps',
                tipo: 'Máquina',
                seriesReps: '4x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/leg_extension.png',
                series: '4',
                repeticiones: '15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Cuádriceps',
              ),
              Ejercicio(
                nombre: 'Curl Femoral Sentado',
                tipo: 'Máquina',
                seriesReps: '4x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/hamstring_curl.png',
                series: '4',
                repeticiones: '15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Isquiosurales',
              ),
            ],
          ),
        ],
      );

      // --- NEW: RUTINA AVANZADA (ARNOLD SPLIT) ---
      final rutinaArnoldSplit = RutinaAdaptacion(
        id: 'arnold_split_advanced',
        variante: '6 Días - Arnold',
        level: 'advanced',
        tags: ['arnold', 'hypertrophy', '6-days'],
        dias: [
          DiaRutina(
            nombreDia: 'Lunes: Pecho/Espalda',
            ejercicios: [
              Ejercicio(
                nombre: 'Press de Banca Plano',
                tipo: 'Barra',
                seriesReps: '4x6-8',
                descanso: '0 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '4',
                repeticiones: '6-8',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Pecho',
                isSuperset: true,
                supersetGroupId: 1,
              ),
              Ejercicio(
                nombre: 'Dominadas Lastradas',
                tipo: 'Peso Corporal',
                seriesReps: '4x6-8',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
                series: '4',
                repeticiones: '6-8',
                tipoDeEquipo: 'Bodyweight',
                musculoObjetivo: 'Espalda',
                isSuperset: true,
                supersetGroupId: 1,
              ),
              Ejercicio(
                nombre: 'Press Inclinado con Mancuernas',
                tipo: 'Mancuernas',
                seriesReps: '4x8-10',
                descanso: '0 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '4',
                repeticiones: '8-10',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Pecho Superior',
                isSuperset: true,
                supersetGroupId: 2,
              ),
              Ejercicio(
                nombre: 'Remo con Barra',
                tipo: 'Barra',
                seriesReps: '4x8-10',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                series: '4',
                repeticiones: '8-10',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Espalda Baja',
                isSuperset: true,
                supersetGroupId: 2,
              ),
              Ejercicio(
                nombre: 'Aperturas en Polea',
                tipo: 'Máquina',
                seriesReps: '3x15',
                descanso: '0 seg',
                urlGif: 'assets/images/exercises/pushup.png',
                series: '3',
                repeticiones: '15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Pecho',
                isSuperset: true,
                supersetGroupId: 3,
              ),
              Ejercicio(
                nombre: 'Pullover con Mancuerna',
                tipo: 'Mancuerna',
                seriesReps: '3x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
                series: '3',
                repeticiones: '15',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Dorsales',
                isSuperset: true,
                supersetGroupId: 3,
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Martes: Hombros/Brazos',
            ejercicios: [
              Ejercicio(
                nombre: 'Press Militar Sentado',
                tipo: 'Mancuernas',
                seriesReps: '4x8-10',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '4',
                repeticiones: '8-10',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Hombros',
              ),
              Ejercicio(
                nombre: 'Elevaciones Laterales',
                tipo: 'Mancuernas',
                seriesReps: '4x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                series: '4',
                repeticiones: '15',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Hombros Laterales',
                intensityTechnique: 'Dropset al fallo',
              ),
              Ejercicio(
                nombre: 'Curl con Barra EZ',
                tipo: 'Barra',
                seriesReps: '4x10-12',
                descanso: '0 seg',
                urlGif: 'assets/images/exercises/biceps_curl.png',
                series: '4',
                repeticiones: '10-12',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Bíceps',
                isSuperset: true,
                supersetGroupId: 4,
              ),
              Ejercicio(
                nombre: 'Press Francés',
                tipo: 'Barra',
                seriesReps: '4x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/triceps_extension.png',
                series: '4',
                repeticiones: '10-12',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Tríceps',
                isSuperset: true,
                supersetGroupId: 4,
              ),
              Ejercicio(
                nombre: 'Curl Martillo',
                tipo: 'Mancuernas',
                seriesReps: '3x12',
                descanso: '0 seg',
                urlGif: 'assets/images/exercises/biceps_curl.png',
                series: '3',
                repeticiones: '12',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Braquial',
                isSuperset: true,
                supersetGroupId: 5,
              ),
              Ejercicio(
                nombre: 'Extensión en Polea Alta',
                tipo: 'Máquina',
                seriesReps: '3x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/triceps_extension.png',
                series: '3',
                repeticiones: '15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Tríceps',
                isSuperset: true,
                supersetGroupId: 5,
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Miércoles: Piernas/Abs',
            ejercicios: [
              Ejercicio(
                nombre: 'Sentadilla High Bar',
                tipo: 'Barra',
                seriesReps: '5x5',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/squat.png',
                series: '5',
                repeticiones: '5',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Cuádriceps',
              ),
              Ejercicio(
                nombre: 'Peso Muerto Rumano',
                tipo: 'Barra',
                seriesReps: '4x8-10',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/hamstring_curl.png',
                series: '4',
                repeticiones: '8-10',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Isquiosurales',
              ),
              Ejercicio(
                nombre: 'Prensa de Piernas',
                tipo: 'Máquina',
                seriesReps: '4x12-15',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/leg_press.png',
                series: '4',
                repeticiones: '12-15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Piernas',
                intensityTechnique: 'Pausa Descanso',
              ),
              Ejercicio(
                nombre: 'Extensiones de Cuádriceps',
                tipo: 'Máquina',
                seriesReps: '3x15',
                descanso: '0 seg',
                urlGif: 'assets/images/exercises/leg_extension.png',
                series: '3',
                repeticiones: '15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Cuádriceps',
                isSuperset: true,
                supersetGroupId: 6,
              ),
              Ejercicio(
                nombre: 'Curl Femoral',
                tipo: 'Máquina',
                seriesReps: '3x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/hamstring_curl.png',
                series: '3',
                repeticiones: '15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Isquiosurales',
                isSuperset: true,
                supersetGroupId: 6,
              ),
              Ejercicio(
                nombre: 'Elevaciones de Piernas Colgado',
                tipo: 'Peso Corporal',
                seriesReps: '4xAl Fallo',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/plank.png',
                series: '4',
                repeticiones: 'Fallo',
                tipoDeEquipo: 'Bodyweight',
                musculoObjetivo: 'Abdominales Inferiores',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Jueves: Pecho/Espalda',
            ejercicios: [
              Ejercicio(
                nombre: 'Press Dominadas Lastradas',
                tipo: 'Peso Corporal',
                seriesReps: '4x8',
                descanso: '0 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
                series: '4',
                repeticiones: '8',
                tipoDeEquipo: 'Bodyweight',
                musculoObjetivo: 'Espalda',
                isSuperset: true,
                supersetGroupId: 7,
              ),
              Ejercicio(
                nombre: 'Press Inclinado Barra',
                tipo: 'Barra',
                seriesReps: '4x8',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '4',
                repeticiones: '8',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Pecho',
                isSuperset: true,
                supersetGroupId: 7,
              ),
              Ejercicio(
                nombre: 'Remo en Polea Baja',
                tipo: 'Máquina',
                seriesReps: '4x10-12',
                descanso: '0 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                series: '4',
                repeticiones: '10-12',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Dorsales',
                isSuperset: true,
                supersetGroupId: 8,
              ),
              Ejercicio(
                nombre: 'Press Plano Mancuernas',
                tipo: 'Mancuernas',
                seriesReps: '4x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '4',
                repeticiones: '10-12',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Pecho',
                isSuperset: true,
                supersetGroupId: 8,
              ),
              Ejercicio(
                nombre: 'Jalón con Brazos Rectos',
                tipo: 'Máquina',
                seriesReps: '3x15',
                descanso: '0 seg',
                urlGif: 'assets/images/exercises/lat_pulldown.png',
                series: '3',
                repeticiones: '15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Dorsales',
                isSuperset: true,
                supersetGroupId: 9,
              ),
              Ejercicio(
                nombre: 'Cruces en Polea',
                tipo: 'Máquina',
                seriesReps: '3x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/pushup.png',
                series: '3',
                repeticiones: '15',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Pecho interno',
                isSuperset: true,
                supersetGroupId: 9,
                intensityTechnique: 'Dropset',
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Viernes: Hombros/Brazos',
            ejercicios: [
              Ejercicio(
                nombre: 'Press Militar de Pie con Barra',
                tipo: 'Barra',
                seriesReps: '4x6-8',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/machine_press.png',
                series: '4',
                repeticiones: '6-8',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Hombros',
              ),
              Ejercicio(
                nombre: 'Remo al Mentón',
                tipo: 'Barra',
                seriesReps: '4x10-12',
                descanso: '0 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                series: '4',
                repeticiones: '10-12',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Hombros Laterales',
                isSuperset: true,
                supersetGroupId: 10,
              ),
              Ejercicio(
                nombre: 'Elevaciones Posteriores',
                tipo: 'Mancuernas',
                seriesReps: '4x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/dumbbell_row.png',
                series: '4',
                repeticiones: '15',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Hombros Posteriores',
                isSuperset: true,
                supersetGroupId: 10,
              ),
              Ejercicio(
                nombre: 'Curl Predicador',
                tipo: 'Máquina',
                seriesReps: '4x10-12',
                descanso: '0 seg',
                urlGif: 'assets/images/exercises/biceps_curl.png',
                series: '4',
                repeticiones: '10-12',
                tipoDeEquipo: 'Machine',
                musculoObjetivo: 'Bíceps Aislado',
                isSuperset: true,
                supersetGroupId: 11,
              ),
              Ejercicio(
                nombre: 'Copa Tríceps a 2 Manos',
                tipo: 'Mancuerna',
                seriesReps: '4x10-12',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/triceps_extension.png',
                series: '4',
                repeticiones: '10-12',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Tríceps',
                isSuperset: true,
                supersetGroupId: 11,
              ),
            ],
          ),
          DiaRutina(
            nombreDia: 'Sábado: Piernas/Abs',
            ejercicios: [
              Ejercicio(
                nombre: 'Sentadilla Frontal',
                tipo: 'Barra',
                seriesReps: '4x8',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/squat.png',
                series: '4',
                repeticiones: '8',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Cuádriceps frontal',
              ),
              Ejercicio(
                nombre: 'Hip Thrust',
                tipo: 'Barra',
                seriesReps: '4x10-12',
                descanso: '120 seg',
                urlGif: 'assets/images/exercises/lunge.png',
                series: '4',
                repeticiones: '10-12',
                tipoDeEquipo: 'Barbell',
                musculoObjetivo: 'Glúteos',
              ),
              Ejercicio(
                nombre: 'Estocadas Búlgaras',
                tipo: 'Mancuernas',
                seriesReps: '4x10/pierna',
                descanso: '90 seg',
                urlGif: 'assets/images/exercises/lunge.png',
                series: '4',
                repeticiones: '10 / pierna',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Piernas',
              ),
              Ejercicio(
                nombre: 'Elevación de Talones a un Pie',
                tipo: 'Mancuerna',
                seriesReps: '4x15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/squat.png',
                series: '4',
                repeticiones: '15',
                tipoDeEquipo: 'Dumbbell',
                musculoObjetivo: 'Pantorrillas',
                intensityTechnique: 'Myo-Reps',
              ),
              Ejercicio(
                nombre: 'Rueda Abdominal (Ab Wheel)',
                tipo: 'Bodyweight',
                seriesReps: '4x10-15',
                descanso: '60 seg',
                urlGif: 'assets/images/exercises/plank.png',
                series: '4',
                repeticiones: '10-15',
                tipoDeEquipo: 'Bodyweight',
                musculoObjetivo: 'Core',
              ),
            ],
          ),
        ],
      );

      // Usamos SetOptions(merge: true) sugeridamente de acá en adelante si se quisiera no pisar estado local.
      // Por simplicidad para el seed general y asegurar que se refresque la última versión, usamos el clásico set.
      await collection.doc(rutina3Dias.id).set(rutina3Dias.toFirestore());
      await collection.doc(rutina5Dias.id).set(rutina5Dias.toFirestore());
      await collection
          .doc(rutinaPrincipiante3Dias.id)
          .set(rutinaPrincipiante3Dias.toFirestore());
      await collection
          .doc(rutinaPrincipiante5Dias.id)
          .set(rutinaPrincipiante5Dias.toFirestore());

      await collection
          .doc(rutinaIntermedia3Dias.id)
          .set(rutinaIntermedia3Dias.toFirestore(), SetOptions(merge: true));
      await collection
          .doc(rutinaIntermedia5Dias.id)
          .set(rutinaIntermedia5Dias.toFirestore(), SetOptions(merge: true));

      await collection
          .doc(rutinaArnoldSplit.id)
          .set(rutinaArnoldSplit.toFirestore(), SetOptions(merge: true));

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('¡Datos inyectados en Firestore con éxito!'),
          backgroundColor: Colors.green,
        ),
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error al inyectar: \$e'),
          backgroundColor: Colors.red,
        ),
      );
    }
  }
}
