name = "pitbull-gym-checkout"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Variables de entorno → definir en Cloudflare Dashboard
# Settings → Variables → MP_ACCESS_TOKEN = tu_token_de_produccion
[vars]
ALIAS = "pitbullgym"
